[[plugins]]
repo = '~/.cache/dein/repos/github.com/Shougo/dein.vim'


[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''


[[plugins]]
repo = 'jonathanfilip/vim-lucius'
hook_add = '''
  set background=dark
  colorscheme lucius
  "au MyAutoCmd VimEnter * nested colorscheme hybrid
'''


[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''


[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

if has('conceal')
  set conceallevel=2 concealcursor=niv
endif
'''


[[plugins]]
repo = 'Shougo/neosnippet-snippets'
hook_add = '''
  let g:neosnippet#snippets_directory = '$HOME/.config/nvim/snippets/'
'''


[[plugins]]
repo = 'vim-airline/vim-airline'


[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  nnoremap <silent> ,gg :<C-u>GitGutterToggle<CR>
  nnoremap <silent> ,gh :<C-u>GitGutterLineHighlightsToggle<CR>
  nnoremap <silent> gn :<C-u>GitGutterNextHunk<CR>
  nnoremap <silent> gp :<C-u>GitGutterPrevHunk<CR>
  set updatetime=100
'''


[[plugins]]
repo = 'tpope/vim-surround'


[[plugins]]
repo = 'tpope/vim-fugitive'


[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'


[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'


[[plugins]]
repo = 'cohama/lexima.vim'


[[plugins]]
repo = 'w0rp/ale'


[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  autocmd StdinReadPre * let s:std_in=1
  autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
  map <C-n> :NERDTreeToggle<CR>
'''
