[[plugins]]
repo = 'Shougo/denite.nvim'
on_event = 'BufRead'
# TODO: customize for me
hook_add = '''
'''
hook_post_source = '''
call denite#custom#var('file_rec', 'command',
\ ['pt', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', ''])
call denite#custom#var('grep', 'command',
\ ['pt', '--nogroup', '--nocolor', '--smart-case', '--hidden'])
call denite#custom#var('grep', 'default_opts', [])
call denite#custom#var('grep', 'recursive_opts', [])
'''


[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']


[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_add = '''
  let g:deoplete#sources#jedi#python_path = $HOME . '/.pyenv/shims/python'
'''


[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'


[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'
hook_add = '''
  let g:flake8_show_in_gutter=1
'''


[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'


[[plugins]]
repo = 'lilydjwg/colorizer'
on_ft = ['css', 'html', 'sass', 'scss', 'vim', 'less', 'md', 'tmux']


[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']


[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_add = '''
  let g:rustfmt_autosave = 1
'''


[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1


[[plugins]]
repo = "posva/vim-vue"
on_ft = ["vue"]


[[plugins]]
repo = 'thinca/vim-showtime'
on_cmd = ['ShowtimeStart']


[[plugins]]
repo = 'flowtype/vim-flow'
on_ft = ['javascript']


[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'typescript']
hook_add = '''
  autocmd ColorScheme * highlight jsxComponentName ctermfg=030 guifg=#25baba
  autocmd ColorScheme * highlight jsxPunct         ctermfg=031 guifg=#0087af
  autocmd ColorScheme * highlight jsxCloseString   ctermfg=031 guifg=#0087af
'''


[[plugins]]
repo = 'yasuhiroki/circleci.vim'
on_ft = ['yaml']


[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']
