[[plugins]]
repo = '~/.cache/dein/repos/github.com/Shougo/dein.vim'


[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''


[[plugins]]
repo = 'jonathanfilip/vim-lucius'
hook_add = '''
  set background=dark
  colorscheme lucius
  "au MyAutoCmd VimEnter * nested colorscheme hybrid
'''


[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''


[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

if has('conceal')
  set conceallevel=2 concealcursor=niv
endif
'''


[[plugins]]
repo = 'Shougo/neosnippet-snippets'
hook_add = '''
  let g:neosnippet#snippets_directory = '$HOME/.config/nvim/snippets/'
'''


[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline_section_b = ''
  let g:airline_section_y = ''
  if !exists('g:airline_symbols')
    let g:airline_symbols = {}
  endif
  let g:airline_symbols.linenr = ''
  let g:airline_symbols.maxlinenr = ''
'''


[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  nnoremap <silent> ,gg :<C-u>GitGutterToggle<CR>
  nnoremap <silent> ,gh :<C-u>GitGutterLineHighlightsToggle<CR>
  nnoremap <silent> gn :<C-u>GitGutterNextHunk<CR>
  nnoremap <silent> gp :<C-u>GitGutterPrevHunk<CR>
  let g:gitgutter_sign_added = '●'
  let g:gitgutter_sign_modified = '●'
  let g:gitgutter_sign_removed = '●'
  let g:gitgutter_sign_modified_removed = '●'
  set updatetime=100
'''


[[plugins]]
repo = 'tpope/vim-surround'


[[plugins]]
repo = 'tpope/vim-fugitive'


[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'


[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'


[[plugins]]
repo = 'w0rp/ale'


[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  map <C-n> :NERDTreeToggle<CR>
'''


[[plugins]]
repo = 'simeji/winresizer'


[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  let g:EasyMotion_do_mapping = 0
  let g:EasyMotion_smartcase = 1
  map <Leader>s <Plug>(easymotion-s2)
  map <Leader>j <Plug>(easymotion-j)
  map <Leader>k <Plug>(easymotion-k)

  let g:EasyMotion_keys = 'ASDFGHJKLQWERTYUIOPZXCVBNM;'
  let g:EasyMotion_use_upper = 1
  let g:EasyMotion_enter_jump_first = 1

  hi link EasyMotionTarget Statement
  hi link EasyMotionShade  Comment
  hi link EasyMotionTarget2First Statement
  hi link EasyMotionTarget2Second Directory
'''
