[cmd_duration]
min_time = 5000 # ms

[aws]
symbol = " "

[conda]
symbol = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[java]
symbol = " "
style = "fg:#DA89A2"

[julia]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
disabled = true

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
