#!/usr/bin/env bash
git secrets --pre_commit_hook -- "$@"

BRANCH=`git branch --contains | cut -d " " -f 2`

if [ $BRANCH = 'master' ]; then
  echo 'masterブランチはcommit禁止です';
  echo '問題ない場合は --no-verify オプションを利用';
  exit 1;
fi

